# Generated by Django 5.2.6 on 2025-09-18 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_customuser_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_varified",
            field=models.BooleanField(default=False),
        ),
    ]
