# Generated by Django 5.2.6 on 2025-09-18 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_customuser_is_varified"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="token",
            field=models.PositiveIntegerField(null=True),
        ),
    ]
