# Generated by Django 5.2.6 on 2025-09-16 15:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='products',
            new_name='product_id',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='user',
            new_name='user_id',
        ),
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together={('user_id', 'product_id')},
        ),
    ]
