# Generated by Django 5.2.6 on 2025-09-16 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='mobile',
            field=models.CharField(max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='o_division',
            field=models.CharField(max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
